# Exercise 2.B Cleaning Up Data

In [13]:
import numpy as np
import pandas as pd

In [14]:
df = pd.read_csv('test_data.csv')
df

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [15]:
df.describe()

            ID       Age      Score
count  8.00000   6.00000   7.000000
mean   4.50000  25.00000  66.285714
std    2.44949   6.78233  32.576650
min    1.00000  18.00000  -1.000000
25%    2.75000  19.75000  60.000000
50%    4.50000  23.50000  78.000000
75%    6.25000  29.50000  87.500000
max    8.00000  35.00000  92.000000

## Filtering a DataFrame

In [16]:
df_18up = df[(df['Age'] > 18)]
df_18up

   ID     Name   Age     City  Score
0   1   Alicia  25.0       NY   85.0
2   3  Charlie  22.0  Chicago   -1.0
3   4  Dominic  19.0  Houston   65.0
4   5      Eve  31.0  Phoenix   78.0
5   6    Frank  35.0   Boston    NaN

In [17]:
df_51to99 = df[(df['Score'] > 50) & (df['Score'] < 100)] #Remember to use '&' for AND in conditional logic

df_51to99

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

## Modifying a DataFrame

In [18]:
df_cleaned = df

for x in df.index:
    if df.loc[x, 'Score'] < 0:
        df.drop(x, inplace=True)

df_cleaned

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [19]:
for x in df.index:
    if df.loc[x, 'City'] == 'City':
        df.drop(x, inplace=True)

df_cleaned

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [20]:
df_cleaned.drop(columns=['City'], inplace=True)
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob   NaN   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace   NaN   55.0
7   8    Heidi  18.0   90.0

In [21]:
#Can use fillna.df_cleaned['Age].mean() instead of fillna.(25) from the describe info above.
df_cleaned['Age'] = df_cleaned['Age'].fillna(25)

df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.0   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace  25.0   55.0
7   8    Heidi  18.0   90.0

In [22]:
df_cleaned['Score'] = df_cleaned['Score'].replace(0, 66.3)

df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.0   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace  25.0   55.0
7   8    Heidi  18.0   90.0

In [23]:
df_cleaned = df_cleaned.dropna()

df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.0   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
6   7    Grace  25.0   55.0
7   8    Heidi  18.0   90.0

In [24]:
df_cleaned = df.set_index('ID')

df_cleaned

       Name   Age  Score
ID
1    Alicia  25.0   85.0
2       Bob  25.0   92.0
4   Dominic  19.0   65.0
5       Eve  31.0   78.0
6     Frank  35.0    NaN
7     Grace  25.0   55.0
8     Heidi  18.0   90.0