# Exercise 2.C Working with Multiple DataFrames

In [1]:
import numpy as np
import pandas as pd

## Basic Aggregations

In [3]:
data = {'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East',
'West', 'North'],
'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]}

df_sales = pd.DataFrame(data)

df_sales

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

In [5]:
df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']

df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

In [9]:
print(f'Sum of Units_Sold: {df_sales['Units_Sold'].sum()}')

print(f'Sum of Revenue: {df_sales['Revenue'].sum()}')

Sum of Units_Sold: 105
Sum of Revenue: 16000

In [ ]:
print(f'Mean of Units_Sold: {df_sales['Units_Sold'].mean().round(2)}')
print(f'Mean of Revenue: {df_sales['Revenue'].mean().round(2)}')
#learned how to use round with sum and mean from in class!

Mean of Units_Sold: 11.67
Mean of Revenue: 1777.78

## Grouping Data