# Exercise 2.C Working with Multiple DataFrames

In [1]:
import numpy as np
import pandas as pd

## Basic Aggregations

In [2]:
data = {'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East',
'West', 'North'],
'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]}

df_sales = pd.DataFrame(data)

df_sales

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

In [3]:
df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']

df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

In [4]:
print(f'Sum of Units_Sold: {df_sales['Units_Sold'].sum()}')

print(f'Sum of Revenue: {df_sales['Revenue'].sum()}')

Sum of Units_Sold: 105
Sum of Revenue: 16000

In [5]:
print(f'Mean of Units_Sold: {df_sales['Units_Sold'].mean().round(2)}')
print(f'Mean of Revenue: {df_sales['Revenue'].mean().round(2)}')
#learned you could  use round with sum and mean from in class!

Mean of Units_Sold: 11.67
Mean of Revenue: 1777.78

## Grouping Data

In [6]:
df_sales.groupby('Product')[['Units_Sold', 'Revenue']].sum()

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

In [7]:
df_sales.groupby('Region')[['Units_Sold', 'Revenue']].mean().round(2)

        Units_Sold  Revenue
Region
East         15.00   2000.0
North        11.67   1750.0
South        15.00   2625.0
West          5.00    750.0

In [8]:
df_sales.groupby(['Product', 'Region'])[['Units_Sold', 'Revenue']].sum()

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

In [11]:
df_sales.sort_values(by='Units_Sold')

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

In [10]:
df_sales.sort_values(by='Revenue', ascending=False)

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
8       C  North          15    150     2250
5       C  South          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

In [14]:
df_sales['Revenue_Rank'] = df_sales['Revenue'].rank(ascending=False)

df_sales.sort_values(by='Revenue_Rank', ascending=False)

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
3       A   West           5    100      500           9.0
0       A  North          10    100     1000           7.0
6       A   East          10    100     1000           7.0
7       B   West           5    200     1000           7.0
4       B  North          10    200     2000           5.0
5       C  South          15    150     2250           3.5
8       C  North          15    150     2250           3.5
1       B  South          15    200     3000           1.5
2       C   East          20    150     3000           1.5

## Merging DataFrames

In [15]:
product_data = {
    'Product': ['A', 'B', 'C'],
    'Category': ['Electronics', 'Furniture', 'Appliances']
}

df_products = pd.DataFrame(product_data)

df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

In [ ]:
df_merged = pd.merge(df_sales, df_products, on='Product')

df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000           7.0  Electronics
1       B  South          15    200     3000           1.5    Furniture
2       C   East          20    150     3000           1.5   Appliances
3       A   West           5    100      500           9.0  Electronics
4       B  North          10    200     2000           5.0    Furniture
5       C  South          15    150     2250           3.5   Appliances
6       A   East          10    100     1000           7.0  Electronics
7       B   West           5    200     1000           7.0    Furniture
8       C  North          15    150     2250           3.5   Appliances

In [17]:
df_merged.groupby('Category')['Revenue'].sum()

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64